// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "routes/home.page.tsx": {
    id: "routes/home.page";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home.page": typeof import("./src/routes/home.page.tsx");
};